cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('account/', include('account.urls')),
    path('files/', include('files.urls', namespace='files')),
    path('search/', include('search.urls', namespace='search')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('discounts/', include('discounts.urls', namespace='discounts')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('warehouses/', include('warehouses.urls', namespace='warehouses')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from . import report_views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),

    path('purchase/create/', views.purchase_create, name='purchase_create'),
    path('purchase/list/', views.purchase_list, name='purchase_list'),
    path('purchase/edit/<int:purchase_id>/', views.purchase_update, name='purchase_update'), # for updating main purchase model

    path('purchase/<int:purchase_id>/', views.purchase_details, name='purchase_details'),

    path('purchase/back-to-draft<int:purchase_id>/', views.back_to_draft_purchase, name='back_to_draft_purchase'),

    # path('purchase/<int:purchase_id>/add/<int:product_id>/', views.purchase_details, name='purchase_add_line'),
    path('purchase/add-line/<int:purchase_id>/<int:product_id>/<str:variation>/', views.purchase_line_add, name='purchaseline_add'),
    path('purchase/add-line/<int:purchase_id>/<int:product_id>/<str:variation>/<int:purchaseline_id>/', views.purchase_line_add, name='purchaseline_update'),
    path('purchaseline/remove/<int:purchaseline_id>/', views.purchaseline_remove, name='purchaseline_remove'),

    path('purchase/<int:purchase_id>/add/<int:product_id>/<str:variation>/', views.purchase_details, name='purchase_add_line_v'),

    path('purchase/price-management/<int:purchase_id>/<int:product_id>/', views.price_management, name='price_management'),
    path('purchase/price-management/remove-price/<int:purchase_id>/<int:product_id>/<str:variation>/', views.price_remove, name='price_remove'),

    path('purchase/checkout/<int:purchase_id>/', views.purchase_checkout, name='purchase_checkout'),

    path('report/sales-by-days/<int:days>/', report_views.sales_by_days, name='sales_by_days'),
    path('report/sales-by-date/<str:date>/', report_views.sales_by_days, name='sales_by_date'),

    path('report/best_selling_books/', report_views.best_selling_books, name='best_selling_books'),
]

staff/urls.py
from django.urls import path

from . import views
from .views import ProductCreate
from warehouses.views import refund_from_client, refund_list_client

app_name = 'staff'


urlpatterns = [
    # path('sales/', views.sales, name='sales_list'),
    path('orders/details/<int:pk>/', views.order_detail_for_admin, name='order_detail_for_admin'),
    path('orders/shipping/<int:order_id>/', views.order_shipping, name='order_shipped'),

    path('orders/full-shipped-list/', views.full_shipped_list, name='full_shipped_list'),
    path('orders/full-shipped-list/<str:date>/', views.full_shipped_list, name='full_shipped_list_date'),
    # path('orders/sipping/<int:order_id>/', views.order_shipping, name='order_shipping'),
    path('orders/drafts/', views.draft_orders, name='draft_orders'),
    path('orders/remove-draft/<int:order_id>/', views.remove_draft_order, name='remove_draft_order'),

    path('orders/create/', views.order_create, name='order_create'),
    # path('orders/', views.orders, name='order_list'),
    # path('orders/<str:channel>/', views.orders, name='order_list_by_channel'),
    # path('orders/<str:channel>/<str:period>/', views.orders, name='order_list_by_channel_period'),
    path('orders/<str:channel>/<str:period>/', views.orders, name='order_list'),
    path('orders/<str:channel>/<str:period>/<str:filter>/', views.orders, name='order_list_filter'),

    path('sales/countries/', views.order_list_by_country, name='order_list_by_country'),
    path('sales/countries/<str:country_code>/', views.order_list_by_country, name='order_list_by_country'),

    path('sales/vendor/', views.sales_by_vendor, name='sales_by_vendor'),
    path('sales/vendor/<int:vendor_id>/<str:date>/', views.sales_by_vendor, name='sales_by_vendor'),


    path('invoice/create/', views.invoice_create, name='invoice_create'),
    path('invoice/create/<int:order_id>/', views.invoice_create, name='invoice_create'),
    path('invoice/create/<int:order_id>/<int:book_id>/', views.invoice_create, name='invoice_add_book'),
    path('invoice/create/<int:order_id>/<int:book_id>/<str:variation>/', views.invoice_create, name='invoice_add_book_v'),

    path('invoice/create/new_order/<int:book_id>/', views.invoice_create, name='invoice_new_add_book'),
    path('invoice/create/new_order/<int:book_id>/<str:variation>/', views.invoice_create, name='invoice_new_add_book_v'),

    path('invoice/create/<int:order_id>/add-client/', views.invoice_create_add_client, name='invoice_add_client'),
    path('invoice/create/<int:order_id>/add-client/<int:client_id>/', views.invoice_create_add_client, name='invoice_add_client_ok'),
    path('invoice/remove-client/<int:order_id>/', views.remove_client_from_order, name='remove_client_from_order'),

    path('invoice/create/line-update/<int:order_id>/<int:orderline_id>/', views.orderline_update, name='orderline_update'),
    path('invoice/checkout/<int:order_id>/', views.invoice_checkout, name='invoice_checkout'),
    path('invoice/checkout/<int:order_id>/<int:client_id>/', views.invoice_checkout, name='invoice_checkout_client'),
    path('invoice/checkout/credit-pay/<int:order_id>/<int:client_id>/', views.invoice_checkout_credit, name='invoice_checkout_client_credit'),
    path('invoice/checkout/credit-remove/<int:order_id>/', views.invoice_remove_credit, name='invoice_remove_credit'),

    path('invoice/back-to-draft/<int:order_id>/', views.invoice_back_to_draft, name='invoice_back_to_draft'),
    path('invoice/payment-manage/<int:order_id>/', views.order_payment_manage, name='order_payment_manage'),

    path('warehouse/', views.warehouse, name='warehouse'),
    path('warehouse/sold-products/<int:days>/', views.sold_products, name='sold_products'),
    path('warehouse/sold-products/date/<str:date>/', views.sold_products, name='sold_products_date'),
    path('warehouse/sold-products/period/<str:period>/', views.sold_products, name='sold_products_date_period'),

    path('warehouse/purchased-products/', views.purchased_products, name='purchased_products'),
    path('warehouse/refund/client/', refund_from_client, name="refund_from_client"),
    path('warehouse/refund/client/list/', refund_list_client, name="refund_list_client"),

    path('warehouse/zero-stock-list/', views.zero_stock_list, name="zero_stock_list"),

    path('products/', views.products, name='products'),
    path('products/create/', views.product_create, name='product_create'),
    # path('products/update/<int:product_id>/', views.product_update, name='product_update'),
    path('products/update/<int:product_id>/', views.product_create, name='product_update'),
    path('products/image-management/<int:product_id>/', views.image_management, name='image_management'),
    path('products/image-remove/<int:image_id>/<int:product_id>/', views.image_remove, name='image_remove'),
    path('products/price-show/<int:product_id>/', views.product_price_show, name='product_price_show'),

    path('products/collection-management/', views.collection_management, name='collection_management'),
    path('products/collection-management/edit/<int:product_id>/', views.collection_management_edit, name='collection_management_edit'),
    path('products/collection-management/edit/<int:product_id>/<str:product_isbn>/', views.collection_management_remove, name='collection_management_remove'),

    path('products/reports/', views.product_reports, name='product_reports'),

    path('categories/', views.category_list, name='categories'),
    path('category/create/', views.category_create, name='category_create'),

    path('vendor/list/', views.vendor_list, name='vendor_list'),
    path('vendor/add/', views.vendor_add, name='vendor_add'),
    path('vendor/edit/<int:vendor_id>/', views.vendor_edit, name='vendor_edit'),

    path('products/used-book/price-management/<int:product_id>/', views.used_book_prices, name="used_book_prices"),
    path('products/price-stock-management/<int:product_id>/', views.product_stock_price_edit, name="product_stock_price_edit"),

    path('products/crafts/', views.craft_list, name="craft_list"),
    path('products/crafts-update/<int:craft_id>/', views.craft_update, name="craft_update"),
    path('products/crafts-create/', views.craft_update, name="craft_create"),
]

staff/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from products.models import Product, Good, Category, Craft, Image, Publisher
from orders.models import Order, OrderLine


class ProductCreateForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [
            'name', 'isbn', 'collection_name', 'number_in_collection', 'category', 'author', 'translator',
            'illustrator', 'latin_name', 'author_latin_name',
            # 'image', 'image_alt',
            'description', 'age_range', 'product_type', 'weight',
            'size', 'cover_type', 'page_number',
            'pub_1', 'pub_2', 'publish_year', # 'publisher', 'publisher_2',
            'edition',
            # 'price', 'stock',
            # 'has_other_prices',
            # 'price_1', 'stock_1', 'price_2', 'stock_2', 'price_3', 'stock_3', 'price_4', 'stock_4', 'price_5', 'stock_5',
            # 'price_used', 'stock_used',
            'store_positon', 'admin_note',
            # 'available', 'available_in_store', 'available_online',
        ]
        labels = {
            'name':_('Name'), 'isbn': _('ISBN'), 'collection_name': _('Collection name'), 'number_in_collection': _('Number in collection'),
            'category': _('Category'), 'author': _('Author'), 'translator': _('Translator'),
            'illustrator': _('Illustrator'), 'latin_name': _('Latin name'), 'author_latin_name': _('Author latin name'),

            'description': _('Description'), 'age_range': _('Age range'), 'product_type': _('Product type'), 'weight': _('Weight'),
            'size': _('Size'), 'cover_type': _('Cover type'), 'page_number': _('Page number'), 'publisher': _('Publisher'), 'publisher_2': _('Publisher 2'),
            'publish_year': _('Publish year'), 'edition': _('Edition'),

            'store_positon': _('Store position'), 'admin_note': _('Admin note'),
        }

class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model = Category
        exclude = ['slug', ]


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ['user', 'token', 'checkout_token' ]

class InvoiceAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quantity'].widget.attrs.update(style='max-width: 2em')
        self.fields['discount'].widget.attrs.update(style='max-width: 4em')

    remove = forms.BooleanField(required=False)

    class Meta:
        model = OrderLine
        fields = ('quantity', 'discount',)
        labels = {
            'quantity': _('Quantity')
        }
        widgets = {
            'quantity': forms.TextInput(attrs={'placeholder': 'quantity'})
        }


class OrderShippingForm(forms.ModelForm):
    # shipped = forms.BooleanField(label='', required=False)
    # STATUS_CHOICES = (
    #     ('', _('')),
    #     ('fulfilled', _('Fully shipped')),
    #     ('unfulfilled', _('Semi shipped'))
    # )
    # shipping_status = forms.ChoiceField(choices = STATUS_CHOICES, label=_("Shipping status"), initial='fulfilled', widget=forms.Select(), required=True)
    # shipping_status = forms.ChoiceField(choices = STATUS_CHOICES, label=_("Shipping status"), widget=forms.Select(), required=True)

    class Meta:
        model = Order
        fields = ['shipped_code', 'shipping_status', 'shipping_time', 'is_packaged']
        labels = {
            'shipped_code': _('Shipping code'),
            'shipping_status': _('Shipping status'),
            'shipping_time': _('Shipping time'),
            'is_packaged': _('Is packaged')
        }
        widgets = {
            'shipped_code': forms.TextInput(attrs={'autofocus': 'autofocus'})
        }


class ProductCollectionForm(forms.Form):
    collection_field = forms.CharField(
        label=_('Related product'),
        max_length=13,
        widget=forms.TextInput(attrs={'placeholder': _('Please add one ISBN each time')})
    )
    # class Meta:
    #     model = Product
    #     fields = ['collection_set',]
    #     labels = {
    #         'collection_set': _('Enter just one ISBN each time')
    #     }
    #     widgets = {
    #         'collection_set': forms.TextInput(attrs={'placeholder': _('Just enter each ISBN in a new line')})
    #     }


class AdminPriceManagementForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [
            'price_used',
            ]
        labels ={
            'price_used': _('Price used'),
        }


class AdminPriceStockManagementForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'price', 'stock', 'price_used', 'stock_used',
            ]
        labels ={
            'price': _('Main price'),
            'stock': _('Main stock'),
            'price_used': _('Used price'),
            'stock_used': _('Used stock'),
        }
        help_texts ={
            'price': _('Only the biggest price'),
            'stock': _('If it\'s bigger than the stock a purchase will create for it'),
            'price_used': _('As same as Bahman key'),
            'stock_used': _('Just for editing the databse for books that is in store but not in database'),
        }


class OnlineAdminPriceStockManagementForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'price',
            # 'stock', 'price_used', 'stock_used',
            ]
        labels ={
            'price': _('Main price'),
            # 'stock': _('Main stock'),
            # 'price_used': _('Used price'),
            # 'stock_used': _('Used stock'),
        }
        help_texts ={
            'price': _('Only the biggest price'),
            # 'stock': _('If it\'s bigger than the stock a purchase will create for it'),
            # 'price_used': _('As same as Bahman key'),
            # 'stock_used': _('Just for editing the databse for books that is in store but not in database'),
        }


class CraftUpdateForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['slug'].required = False

    class Meta:
        model = Product
        fields = [
            'name', 'craft_category', 'barcode_number', 'stock', 'price', 'description', 'available']


class ProductImageManagementForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['file', 'image_alt', 'variation']
        widgets = {
            'image_alt': forms.TextInput(attrs={'placeholder': _('Image alt is a description for defining the image')})
        }


class PublisherUpdateForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ['name', 'url', ]

templates/staff/purchase/_purchase_details_block.html
{% load i18n %}

{% load static %}

{% load humanize %}
<table class="table table-striped">
  <tr>
    <td>{%trans 'Registrar' %}</td>
    <td>{{ purchase.registrar }}</td>
  </tr>
  <tr>
    <td>{%trans 'Approver' %}</td>
    <td>{% if purchase.approver %}{{ purchase.approver }} {% endif %}{% if purchase.approved_date %}- {{ purchase.get_fa_approved }}{% endif %}
    </td>
  </tr>
  <tr>
    <td>{%trans 'Vendor' %}</td>
    <td>{{ purchase.vendor }}</td>
  </tr>
  <tr>
    <td>{%trans 'Paper invoice number' %}</td>
    <td>{% if purchase.paper_invoice_number %}{{ purchase.paper_invoice_number }}{% endif %}</td>
  </tr>
  <tr>
    <td>{%trans 'Payment deadline' %}</td>
    <td>{{ purchase.get_fa_payment }} - {{ purchase.deadline_days }} {% trans 'days is remained' %}</td>
  </tr>
  <tr>
    <td>{%trans 'Purchase status' %}</td>
    <td><span class="badge {% if purchase.status == 'draft' %}bg-warning{% else %}bg-success {% endif %}">{{ purchase.status }} </span></td>
  </tr>

</table>

templates/staff/purchase/_purchase_list_block.html
{% load i18n %}

{% load static %}

{% load humanize %}
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">{% trans 'Image' %}</th>
        <th scope="col">{% trans 'isbn' %}</th>
        <th scope="col">{% trans 'Name' %}</th>
        <th scope="col">{% trans 'Publisher' %}</th>
        <th scope="col">{% trans 'Quantity' %}</th>
        <th scope="col">{% trans 'Price' %}<span class="small"> ({% trans 'Rial' %})</span></th>
        <th scope="col">{% trans 'Price' %}<span class="small"> ({% trans 'Rial' %})</span></th>
        <th scope="col">%</th>
        <th scope="col">{% trans 'Discount' %}</th>
        <th scope="col">{% trans 'Cost' %} ({% trans 'Rial' %})</th>
      </tr>
    </thead>
    <tbody>
      {% for purchase_line in purchase.lines.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="" alt="{{ product.image_alt }}" width="60px" height="auto"></td>
        <td>{{ purchase_line.product.isbn }}</td>
        {% if purchase.status == 'draft' %}
        <td><a href="{% url 'orders:purchaseline_update' purchase_id=purchase.id product_id=purchase_line.product.id variation=purchase_line.variation purchaseline_id=purchase_line.id %}">{{ purchase_line.product }}</a></td>
        {% else %}
        <td>{{ purchase_line.product }}</td>
        {% endif %}
        <td>{% if purchase_line.product.pub_1 %}{{ purchase_line.product.pub_1.name }}{% endif %}</td>
        <td>{{ purchase_line.quantity }}</td>
        <td>{{ purchase_line.price | intcomma:False }}</td>
        <td>{{ purchase_line.get_cost | intcomma:False }}</td>
        <td>{{ purchase_line.discount_percent }}</td>
        <td>{{ purchase_line.discount | intcomma:False }}</td>
        <td>{{ purchase_line.get_cost_after_discount | intcomma:False }}</td>
      </tr>
      {% endfor %}


    <tfoot>
      <tr>
        <th scope="row"></th>
        <td colspan="4">{% trans 'Sum' %}</td>
        <td>{{ purchase.get_total_quantity }}</td>
        <td></td>
        <td>{{ purchase.get_total_cost | intcomma:False}}</td>
        <td></td>
        <td></td>
        <td>{{ purchase.get_cost_after_discount | intcomma:False }}</td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td colspan="9">{% trans 'Overal discount' %}</td>
        <td class="text-danger">{{ purchase.discount | intcomma:False }}</td>

      </tr>
      <tr>
        <th scope="row"></th>
        <td colspan="9">{% trans 'Overal discount percent' %}</td>
        <td class="text-danger">{{ purchase.discount_percent }} %</td>

      </tr>
      <tr>
        <th scope="row"></th>
        <td colspan="9" class="fw-bolder">{% trans 'Payable' %}</td>
        <td class="fw-bolder">{{ purchase.payable | intcomma:False }}</td>
      </tr>
    </tfoot>
    </tbody>
  </table>
</div>

templates/staff/purchase/purchase_details.html
{% extends "_base.html" %}

{% load i18n %}

{% load static %}

{% load humanize %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Purchase details' %}{% endblock %}


{% block purchases-btn %}btn-secondary text-dark{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
  <div class="row">
    <div class="col-md-1">
      {% include "staff/sidebar_staff.html" with barName="purchase" %}
    </div>
    <div class="col-md-11">
      <h2>{% trans 'Purchase' %} {{ purchase.id }} - {{ purchase.vendor }}</h2>
      <div class="">
        {% if purchase.status == 'approved'%}
        {% if request.user.is_manager %}
        <a href="{% url 'orders:back_to_draft_purchase' purchase.id %}" class="btn btn-sm btn-outline-danger">Back to draft</a>
        {% endif %}
        {% endif %}
      </div>
      <div class="">
        {% include 'staff/purchase/_purchase_details_block.html' %}
      </div>
      {% if purchase.status == "draft" %}
      <div class="my-3">
        <form class="" action="." method="post">
          {% csrf_token %}
          {{ search_form | crispy }}
          <input type="submit" class="btn btn-outline-secondary my-3" name="" value="{% trans 'Submit' %}">
        </form>

      </div>
      {% if results %}
      <div class="row">

        {% for result in results %}
        <div class="col-md-4 my-4">

          {# <a href="{% url 'orders:purchase_add_line' purchase_id=purchase.id product_id=result.id %}" class="btn btn-sm btn-success m-1 fs-10 text-right"> #}

          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='new main'%}" class="btn btn-sm btn-success m-1 fs-10 text-right">
            {{ result.name | truncatechars:30 }} - {{ result.publisher | truncatechars:15 }} - {{ result.size }} - {{ result.cover_type }} - {% trans 'Quantity' %} {{ result.stock}} - {{ result.price | intcomma:False }}
          </a>
          {% if result.has_other_prices %}
          {% if result.price_1 %}
          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='new v1' %}" class="btn btn-sm btn-success">{{ result.price_1 | intcomma:False }}</a>
          {% endif %}
          {% if result.price_2 %}
          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='new v2' %}" class="btn btn-sm btn-success">{{ result.price_2 | intcomma:False }}</a>
          {% endif %}
          {% if result.price_3 %}
          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='new v3' %}" class="btn btn-sm btn-success">{{ result.price_3 | intcomma:False }}</a>
          {% endif %}
          {% if result.price_4 %}
          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='new v4' %}" class="btn btn-sm btn-success">{{ result.price_4 | intcomma:False }}</a>
          {% endif %}
          {% if result.price_5 %}
          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='new v5' %}" class="btn btn-sm btn-success">{{ result.price_5 | intcomma:False }}</a>
          {% endif %}
          {% if result.price_used %}
          <a href="{% url 'orders:purchase_add_line_v' purchase_id=purchase.id product_id=result.id variation='used main' %}" class="btn btn-sm btn-warning">{{ result.price_used | intcomma:False }}</a>
          {% endif %}
          {% endif %}
          <a href="{% url 'orders:price_management' product_id=result.id purchase_id=purchase.id %}" class="btn btn-sm btn-success m-1 fs-10 text-right">...</a>
        </div>
        {% endfor %}

      </div>
      {% endif %} {# end of results block #}
      {% endif %} {# end of draft purchase block #}

      <div class="">
        {% include 'staff/purchase/_purchase_list_block.html' %}
        {% comment %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">{% trans 'Image' %}</th>
              <th scope="col">{% trans 'isbn' %}</th>
              <th scope="col">{% trans 'Name' %}</th>
              <th scope="col">{% trans 'Author' %}</th>
              <th scope="col">{% trans 'Publisher' %}</th>
              <th scope="col">{% trans 'Quantity' %}</th>
              <th scope="col">{% trans 'Price' %}</th>
              <th scope="col">{% trans 'Sum' %}</th>
              <th scope="col">{% trans 'Discount' %} </th>
              <th scope="col">{% trans 'Cost' %} ({% trans 'Rial' %})</th>
            </tr>
          </thead>
          <tbody>
            {% for purchase_line in purchase_lines %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="" alt="{{ product.image_alt }}" width="60px" height="auto"></td>
              <td>{{ purchase_line.product.isbn }}</td>
              <td><a href="{% url 'orders:purchaseline_update' purchase_id=purchase.id product_id=purchase_line.product.id variation=purchase_line.variation purchaseline_id=purchase_line.id %}">{{ purchase_line.product }}</a></td>
              <td>{{ purchase_line.product.author }}</td>
              <td>{{ purchase_line.product.publisher }}</td>
              <td>{{ purchase_line.quantity }}</td>
              <td>{{ purchase_line.price | intcomma:False }}</td>
              <td>{{ purchase_line.get_cost | intcomma:False }}</td>
              <td>{{ purchase_line.discount_percent | intcomma:False }}</td>
              {# <!-- TODO: PurchaseLine discount does not calculate correctly --> #}
              <td>{{ purchase_line.discount | intcomma:False }}</td>
              <td>{{ purchase_line.get_cost_after_discount | intcomma:False }}</td>
            </tr>
            {% endfor %}


          <tfoot>
            <tr>
              <th scope="row"></th>
              <td colspan="5">{% trans 'Sum' %}</td>
              <td>{{ purchase.get_total_quantity }}</td>
              <td ></td>
              <td>{{ purchase.get_total_cost | intcomma:False}}</td>
              <td ></td>
              <td>{{ purchase.get_cost_after_discount | intcomma:False }}</td>
            </tr>
            <tr>
              <th scope="row"></th>
              <td colspan="9">{% trans 'Overal discount' %}</td>
              <td class="text-danger">{{ purchase.discount | intcomma:False }}</td>

            </tr>
            <tr>
              <th scope="row"></th>
              <td colspan="9">{% trans 'Overal discount percent' %}</td>
              <td class="text-danger">{{ purchase.discount_percent  }} %</td>

            </tr>
            <tr>
              <th scope="row"></th>
              <td colspan="9" class="fw-bolder">{% trans 'Payable' %}</td>
              <td class="fw-bolder">{{ purchase.payable | intcomma:False }}</td>
            </tr>
          </tfoot>
          </tbody>
        </table>
        {% endcomment %}
      </div>
      <div class="">
        {% if purchase.status == "draft" %}
        <a href="{% url 'orders:purchase_update' purchase.id %}" class="btn btn-outline-secondary ">{% trans 'Edit purchase' %}</a>
        <a href="{% url 'orders:purchase_checkout' purchase.id %}" class="btn btn-outline-success">{% trans 'Purchase checkout' %}</a>
        {% endif %}
      </div>
    </div> <!-- end of col-md-10 -->

  </div> <!-- end of main row -->
</div>
{% endblock %}