cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('account/', include('account.urls')),
    path('files/', include('files.urls', namespace='files')),
    path('search/', include('search.urls', namespace='search')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('discounts/', include('discounts.urls', namespace='discounts')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('warehouses/', include('warehouses.urls', namespace='warehouses')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from . import report_views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),

    path('purchase/create/', views.purchase_create, name='purchase_create'),
    path('purchase/list/', views.purchase_list, name='purchase_list'),
    path('purchase/edit/<int:purchase_id>/', views.purchase_update, name='purchase_update'), # for updating main purchase model

    path('purchase/<int:purchase_id>/', views.purchase_details, name='purchase_details'),

    path('purchase/back-to-draft<int:purchase_id>/', views.back_to_draft_purchase, name='back_to_draft_purchase'),

    # path('purchase/<int:purchase_id>/add/<int:product_id>/', views.purchase_details, name='purchase_add_line'),
    path('purchase/add-line/<int:purchase_id>/<int:product_id>/<str:variation>/', views.purchase_line_add, name='purchaseline_add'),
    path('purchase/add-line/<int:purchase_id>/<int:product_id>/<str:variation>/<int:purchaseline_id>/', views.purchase_line_add, name='purchaseline_update'),
    path('purchaseline/remove/<int:purchaseline_id>/', views.purchaseline_remove, name='purchaseline_remove'),

    path('purchase/<int:purchase_id>/add/<int:product_id>/<str:variation>/', views.purchase_details, name='purchase_add_line_v'),

    path('purchase/price-management/<int:purchase_id>/<int:product_id>/', views.price_management, name='price_management'),
    path('purchase/price-management/remove-price/<int:purchase_id>/<int:product_id>/<str:variation>/', views.price_remove, name='price_remove'),

    path('purchase/checkout/<int:purchase_id>/', views.purchase_checkout, name='purchase_checkout'),

    path('report/sales-by-days/<int:days>/', report_views.sales_by_days, name='sales_by_days'),
    path('report/sales-by-date/<str:date>/', report_views.sales_by_days, name='sales_by_date'),

    path('report/best_selling_books/', report_views.best_selling_books, name='best_selling_books'),
]

shop/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views

app_name = 'shop'

urlpatterns = [
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/<int:image_id>/', views.product_detail, name='product_detail_image'),
    path('product/<int:product_id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('', views.temp_home, name='temp_home'),
    # path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('products/<str:category_slug>/', views.product_list, name='products_list'),

    path('book-search/<str:state>/', views.store_book_search, name='store_book_search'),

    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    path('categories/', views.category_list, name="category_list"),
    path('publishers/', views.publisher_list, name="publisher_list"),
    path('publishers/products/<int:publisher_id>/', views.publisher_products, name="publisher_products"),
    path('publishers/create/', views.publisher_create, name="publisher_create"),
    path('publishers/update/<int:publisher_id>', views.publisher_create, name="publisher_update"),
]

staff/urls.py
from django.urls import path

from . import views
from .views import ProductCreate
from warehouses.views import refund_from_client, refund_list_client

app_name = 'staff'


urlpatterns = [
    # path('sales/', views.sales, name='sales_list'),
    path('orders/details/<int:pk>/', views.order_detail_for_admin, name='order_detail_for_admin'),
    path('orders/shipping/<int:order_id>/', views.order_shipping, name='order_shipped'),

    path('orders/full-shipped-list/', views.full_shipped_list, name='full_shipped_list'),
    path('orders/full-shipped-list/<str:date>/', views.full_shipped_list, name='full_shipped_list_date'),
    # path('orders/sipping/<int:order_id>/', views.order_shipping, name='order_shipping'),
    path('orders/drafts/', views.draft_orders, name='draft_orders'),
    path('orders/remove-draft/<int:order_id>/', views.remove_draft_order, name='remove_draft_order'),

    path('orders/create/', views.order_create, name='order_create'),
    # path('orders/', views.orders, name='order_list'),
    # path('orders/<str:channel>/', views.orders, name='order_list_by_channel'),
    # path('orders/<str:channel>/<str:period>/', views.orders, name='order_list_by_channel_period'),
    path('orders/<str:channel>/<str:period>/', views.orders, name='order_list'),
    path('orders/<str:channel>/<str:period>/<str:filter>/', views.orders, name='order_list_filter'),

    path('sales/countries/', views.order_list_by_country, name='order_list_by_country'),
    path('sales/countries/<str:country_code>/', views.order_list_by_country, name='order_list_by_country'),

    path('sales/vendor/', views.sales_by_vendor, name='sales_by_vendor'),
    path('sales/vendor/<int:vendor_id>/<str:date>/', views.sales_by_vendor, name='sales_by_vendor'),


    path('invoice/create/', views.invoice_create, name='invoice_create'),
    path('invoice/create/<int:order_id>/', views.invoice_create, name='invoice_create'),
    path('invoice/create/<int:order_id>/<int:book_id>/', views.invoice_create, name='invoice_add_book'),
    path('invoice/create/<int:order_id>/<int:book_id>/<str:variation>/', views.invoice_create, name='invoice_add_book_v'),

    path('invoice/create/new_order/<int:book_id>/', views.invoice_create, name='invoice_new_add_book'),
    path('invoice/create/new_order/<int:book_id>/<str:variation>/', views.invoice_create, name='invoice_new_add_book_v'),

    path('invoice/create/<int:order_id>/add-client/', views.invoice_create_add_client, name='invoice_add_client'),
    path('invoice/create/<int:order_id>/add-client/<int:client_id>/', views.invoice_create_add_client, name='invoice_add_client_ok'),
    path('invoice/remove-client/<int:order_id>/', views.remove_client_from_order, name='remove_client_from_order'),

    path('invoice/create/line-update/<int:order_id>/<int:orderline_id>/', views.orderline_update, name='orderline_update'),
    path('invoice/checkout/<int:order_id>/', views.invoice_checkout, name='invoice_checkout'),
    path('invoice/checkout/<int:order_id>/<int:client_id>/', views.invoice_checkout, name='invoice_checkout_client'),
    path('invoice/checkout/credit-pay/<int:order_id>/<int:client_id>/', views.invoice_checkout_credit, name='invoice_checkout_client_credit'),
    path('invoice/checkout/credit-remove/<int:order_id>/', views.invoice_remove_credit, name='invoice_remove_credit'),

    path('invoice/back-to-draft/<int:order_id>/', views.invoice_back_to_draft, name='invoice_back_to_draft'),
    path('invoice/payment-manage/<int:order_id>/', views.order_payment_manage, name='order_payment_manage'),

    path('warehouse/', views.warehouse, name='warehouse'),
    path('warehouse/sold-products/<int:days>/', views.sold_products, name='sold_products'),
    path('warehouse/sold-products/date/<str:date>/', views.sold_products, name='sold_products_date'),
    path('warehouse/sold-products/period/<str:period>/', views.sold_products, name='sold_products_date_period'),

    path('warehouse/purchased-products/', views.purchased_products, name='purchased_products'),
    path('warehouse/refund/client/', refund_from_client, name="refund_from_client"),
    path('warehouse/refund/client/list/', refund_list_client, name="refund_list_client"),

    path('warehouse/zero-stock-list/', views.zero_stock_list, name="zero_stock_list"),

    path('products/', views.products, name='products'),
    path('products/create/', views.product_create, name='product_create'),
    # path('products/update/<int:product_id>/', views.product_update, name='product_update'),
    path('products/update/<int:product_id>/', views.product_create, name='product_update'),
    path('products/image-management/<int:product_id>/', views.image_management, name='image_management'),
    path('products/image-remove/<int:image_id>/<int:product_id>/', views.image_remove, name='image_remove'),
    path('products/price-show/<int:product_id>/', views.product_price_show, name='product_price_show'),

    path('products/collection-management/', views.collection_management, name='collection_management'),
    path('products/collection-management/edit/<int:product_id>/', views.collection_management_edit, name='collection_management_edit'),
    path('products/collection-management/edit/<int:product_id>/<str:product_isbn>/', views.collection_management_remove, name='collection_management_remove'),

    path('products/reports/', views.product_reports, name='product_reports'),

    path('categories/', views.category_list, name='categories'),
    path('category/create/', views.category_create, name='category_create'),

    path('vendor/list/', views.vendor_list, name='vendor_list'),
    path('vendor/add/', views.vendor_add, name='vendor_add'),
    path('vendor/edit/<int:vendor_id>/', views.vendor_edit, name='vendor_edit'),

    path('products/used-book/price-management/<int:product_id>/', views.used_book_prices, name="used_book_prices"),
    path('products/price-stock-management/<int:product_id>/', views.product_stock_price_edit, name="product_stock_price_edit"),

    path('products/crafts/', views.craft_list, name="craft_list"),
    path('products/crafts-update/<int:craft_id>/', views.craft_update, name="craft_update"),
    path('products/crafts-create/', views.craft_update, name="craft_create"),
]

tickets/urls.py
from django.urls import path

from . import views


app_name = 'tickets'


urlpatterns = [
    path('', views.tickets_list, name="tickets_list"),
    path('filter/<str:filter>', views.tickets_list, name="tickets_list_filter"),
    path('details/<int:ticket_id>/', views.ticket_details, name="ticket_details"),
    path('create/', views.create_ticket, name="create_ticket"),
]

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path('pdf/<int:order_id>/', views.make_invoice_pdf, name="make_invoice_pdf"),
    path('pdf/<int:order_id>/print/', views.print_invoice, name="print_invoice"),
    path('pdf/a4/<int:order_id>/', views.make_invoice_pdf_a4, name="make_invoice_pdf_a4"),

    path('print/address/<int:client_id>/<str:kind>/', views.print_address, name="print_address"),

    path('order-export/<str:criteria>/', views.order_export_excel, name="order_export_excel"),
    path('order-export/<str:criteria>/<str:date>/', views.order_export_excel, name="order_export_excel_date"),

    path('draft-order-export/', views.draft_order_export_excel, name="draft_order_export_excel"),
    path('publishers-export/', views.export_publisher, name="export_publisher"),

    path('product-export/', views.product_export_excel, name="product_export_excel"),
    path('used-product-without-price-export/<str:filter>/', views.product_export_excel, name="used_noprice_export_excel"),
    path('used-product-all-export/<str:filter>/', views.product_export_excel, name="used_all_export_excel"),

    path('used-product-before-5/', views.used_product_before_5, name="used_product_before_5"),

    path('qrcode/create/<int:order_id>/<int:payment_id>/', views.qrcode_create, name='qrcode_create'),

    path('export-sold-products/<int:days>/', views.export_excel_sold_products, name="export_excel_sold_products"),
    path('export-sold-products/date/<str:date>/', views.export_excel_sold_products, name="export_excel_sold_products_date"),
    path('export-sold-products/period/<str:period>/', views.export_excel_sold_products, name="export_excel_sold_products_date_period"),

    path('duplicate-book-name/', views.duplicate_book_name, name="duplicate_book_name"),
    path('duplicate-book-name/export', views.duplicate_book_name_export, name="duplicate_book_name_export"),
]

zarinpal/urls.py
from django.urls import path
from . import views


app_name = 'zarinpal'

urlpatterns = [
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
    path('form_verify/', views.form_verify , name='form_verify'),
    path('payment-form/', views.form_payment , name='form_payment'),
    path('payment/create/', views.payment_create , name='payment_create'),
    path('payment-link/<int:pay_id>/', views.send_form_request , name='payment_link_request'),
    path('payments/', views.payment_list , name='payment_list'),
    path('payments/already_paid/', views.already_paid , name='already_paid'),

    path('payment/create/order/<int:order_id>/', views.payment_create_order , name='payment_create_order'),
]

orders/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Order, Purchase, PurchaseLine


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = [
            'client', 'client_phone', 'user_email',
            'shipping_method',
        ]


class OrderAdminCheckoutForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['customer_note'].widget.attrs.update(style='max-height: 4em')

    class Meta:
        model = Order
        fields = [
            'discount', 'channel', 'is_gift', 'paid', 'customer_note',
            'shipping_method', 'shipping_cost', 'shipping_time',
        ]
        labels ={
            'customer_note': _('Notes'),
            'is_gift': _('Is a gift'),
            'channel': _('Cahnnel'),
            'discount': _('Invoice discount'),
            'shipping_method': _('Shipping method'),
            'shipping_cost': _('Shipping cost'),
            'shipping_time': _('Shipping time'),
        }


class OrderPaymentManageForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'pay_receipt', 'paid', 'customer_note', 'shipping_time'
        ]

class PurchaseCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
	    super().__init__(*args, **kwargs)
	    self.fields['vendor'].required = True

    class Meta:
        model = Purchase
        fields = ['vendor', 'deadline_days', 'paper_invoice_number', 'discount', 'discount_percent']
        labels = {
            'vendor': _('Vendor'),
            'deadline_days': _('Payment deadline'),
            'paper_invoice_number': _('Paper invoice number'),
            'discount': _('Invoice overal discount'),
            'discount_percent': _('Overal discount percent'),
        }
        validators = {
            'discount_percent': [MinValueValidator(0), MaxValueValidator(100)]
        }

class PurchaseLineAddForm(forms.ModelForm):

    class Meta:
        model = PurchaseLine
        exclude = ['vendor']


class PriceAddForm(forms.Form):
    STATUS_CHOICES = (
        ('new', _('New')),
        ('used', _('Used')),
    )
    variation = forms.ChoiceField(choices = STATUS_CHOICES)
    price = forms.DecimalField(max_digits=10, decimal_places=0)
    # quantity = forms.IntegerField()


class PurchaseLineUpdateForm(forms.ModelForm):
    class Meta:
        model = PurchaseLine
        fields = [
            'quantity', 'discount', 'discount_percent', 
        ]
        labels = {
            'price': _('Purchase price'),

        }

templates/staff/order_add_client.html
{% extends "_base.html" %}

{% load i18n %}

{% load static %}

{% load humanize %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Invoice create' %}{% endblock %}

{% block slaes-btn %}btn btn-secondary text-dark{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
  <div class="row">
    <div class="col-md-1">
      {% include "staff/sidebar_staff.html" with barName="sales" %}
    </div>
    <div class="col-md-11">
      <div class="client">
        <h3 class="mb-4">{% trans 'Add client to the order' %}</h3>
        <form class="w-50" action="" method="post">
          {{ client_search_form | crispy }}
          <input class="btn btn-outline-secondary my-4" type="submit" name="client" value="{% trans 'Search client' %}">
          {% csrf_token %}
        </form>

        {% if clients %}
        {% for client in clients %}

        <a href="{% url 'staff:invoice_add_client_ok' order_id=order.id client_id=client.id %}" class="btn btn-success m-1">{{ client.first_name }} {{ client.last_name }}- {{ client.phone }}</a>

        {% endfor %}
        {% endif %}


        {% if client_add_notice %}
        <a href="{% url 'client_add' %}/#addClient" onclick="return popitup('/account/client_add/#addClient')" class="btn btn-success">{% trans 'Add client' %}</a>

        {% endif %}

        {% if order.client %}
        <div class="mt-3 mb-4">
          <h3 class="mb-4">{% trans 'Client name' %}</h3>
          <span class=" text-success border border-success rounded p-2 col-md-4"><b>{{ order.client.first_name }} {{ order.client.last_name }}- {{ order.client.phone }}</span>

          <br>
        </div>
        {% endif %}
      </div>
      <div class="">
        <a href="{% url 'staff:invoice_create' order.id %}" class="btn btn-outline-secondary">{% trans 'Back to invoice' %}</a>
      </div>
      <div>


        <div class="">
          <h2 class="my-4">{% trans 'Invoice' %}{% if order %}{% trans 'Number' %}: {{ order.id }}{% endif %}</h2>

          {% include "staff/_order_table.html" %}

        </div>
        <div class="my-5">
          <a href="{% url 'staff:draft_orders' %}" class="btn btn-outline-secondary">{% trans 'Save draft' %}</a>

          <a {% if order and order.lines.all %}href="{% url 'staff:invoice_checkout' order.id %}" class="btn btn-success" {% else %}href="" class="btn btn-outline-success disabled" {% endif%}>{% trans 'Submit' %}</a>

          <a {% if order %} href="{% url 'tools:print_invoice' order.id %}" class="btn btn-outline-secondary my-3" {% else %}href="" class="btn btn-outline-success disabled" {% endif %} target="_blank">{% trans 'Print' %}</a>
          {# <a onclick="window.print();return false;" class="btn btn-outline-secondary">{% trans 'Print' %}</a> #}
          {% if order %}
          <a href="{% url 'tools:make_invoice_pdf' order.id %}" target="_blank" class="btn btn-outline-secondary">PDF</a>
          <a href="{% url 'tools:make_invoice_pdf_a4' order.id %}" target="_blank" class="btn btn-outline-secondary">PDF A4</a>
          {% endif %}
          <a href="{% url 'staff:invoice_create' %}" class="btn btn-outline-secondary">{% trans 'Clear' %}</a>
        </div>
      </div>

    </div>

  </div>

</div>
{% endblock %}

{% block script %}

{% endblock %}

templates/staff/sidebar_staff.html
{% load i18n %}
{% if barName == "products" %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:products'%}">{% trans 'List of products' %}</a>
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:product_create'%}">{% trans 'Create product' %}</a>

  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:collection_management' %}">{% trans 'Collection managment' %}</a>
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'shop:store_book_search' state='used' %}">{% trans 'Search in used books' %}</a>
  <br>
  {#<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:category_create'%}">{% trans 'Create a new category' %}</a>#}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:categories' %}">{% trans 'List of categories' %}</a>
  <br>
  <a href="{% url 'shop:publisher_list' %}" class="btn btn-sm btn-outline-secondary d-block m-1">{% trans 'Publishers' %}</a>
  <a href="{% url 'shop:publisher_create' %}" class="btn btn-sm btn-outline-secondary d-block m-1">{% trans 'Create publisher' %}</a>
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:craft_list' %}">{% trans 'List of crafts' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:craft_create' %}">{% trans 'Create craft product' %}</a>
  {% if request.user.is_superuser %}
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'tools:duplicate_book_name' %}">{% trans 'Duplicate books' %}</a>
  {#<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'tools:export_publisher' %}">{% trans 'Export publishers' %}</a>#}
  {#<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'tools:used_product_before_5' %}">{% trans 'used product sold befor 5 march' %}</a>#}
  {% endif %}

{% endif %}

{% if barName == "sales" %}
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:invoice_create' %}" accesskey="a" data-bs-toggle="tooltip" data-bs-placement="left" title="alt + shift + a">{% trans 'New invoice' %}</a>
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:draft_orders' %}">{% trans 'List of draft orders' %}</a>
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'client_add' %}/#addClient" onclick="return popitup('/account/client_add/#addClient')" class="">{% trans 'Add client' %}</a>
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'zarinpal:payment_create' %}">{% trans 'Create a payment link' %}</a>
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'zarinpal:payment_list' %}">{% trans 'Payment list' %}</a>
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period='all' channel='cashier' %}">{% trans 'Cashier sales' %}</a>
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list_by_country' %}">{% trans 'Sales by country' %}</a>
{% if request.user.is_superuser %}
<a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:sales_by_vendor' %}">{% trans 'Sales by vendor' %}</a>
{% endif %}
{% endif %}

{% if barName == "orders" %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period='all' channel='all' %}">{% trans 'All approved orders' %}</a>
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period='all' channel='collectable' %}">{% trans 'Collectable orders' %}</a>
  {% if yesterday %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period=yesterday channel='collectable' %}">{% trans 'Last day' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period=last_week channel='collectable' %}">{% trans 'Last week' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period=last_month channel='collectable' %}">{% trans 'Last month' %}</a>
  {% endif %}

  <br>
  {% if channel_list %}
  {% for channel in channel_list %}
    <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:order_list' period='all' channel=channel %}">{{ channel }}</a>
  {% endfor %}
  {% endif %}

  <br>
  {% if request.user.is_superuser or request.user.is_manager %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:full_shipped_list' %}">{% trans 'Full shipped list' %}</a>
  {% endif %}
{% endif %}

{% if barName == "purchase" %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'orders:purchase_create' %}">{% trans 'New purchase invoice' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'orders:purchase_list' %}">{% trans 'List of purchases' %}</a>
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:vendor_add' %}">{% trans 'Add vendor' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:vendor_list' %}">{% trans 'Vendor list' %}</a>
{% endif %}

{% if barName == "warehouse" %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:sold_products' days=1 %}">{% trans 'Sold products' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:purchased_products' %}">{% trans 'Purchased products' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:zero_stock_list' %}">{% trans 'Zero stock' %}</a>
  {#<a class="btn btn-sm btn-outline-secondary d-block m-1" href="">{% trans 'Warehouse Managment' %}</a>#}

  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:refund_from_client' %}">{% trans 'Refund a product' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'staff:refund_list_client' %}">{% trans 'List of refunds' %}</a>
{% endif %}

{% if barName == "clients" %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'client_list' %}">{% trans 'List of clients' %}</a>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'client_add' %}" accesskey="c" data-bs-toggle="tooltip" data-bs-placement="left" title="alt + shift + c">{% trans 'Add client' %}</a>
  <br>
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'client_most_valuable' %}">{% trans 'Most valuable clients' %}</a>

{% endif %}

{% if barName == "reports" %}
  {% if request.user.is_superuser or request.user.is_manager %}
  <a class="btn btn-sm btn-outline-secondary d-block m-1" href="{% url 'orders:best_selling_books' %}">{% trans 'Best selling books' %}</a>
  {% endif %}
{% endif %}

{% if barName == "tickets" %}
    <a href="{% url 'tickets:tickets_list' %}" class="btn btn-sm btn-outline-secondary d-block m-1">{% trans 'Tickets list' %}</a>
    <a href="{% url 'tickets:create_ticket' %}" class="btn btn-sm btn-outline-secondary d-block m-1">{% trans 'Create ticket' %}</a>
{% endif %}

{% block script %}
<script language="javascript" type="text/javascript">
  function popitup(url) {
    newwindow = window.open(url, '{{title}}', 'height=350,width=150');
    if (window.focus) {
      newwindow.focus()
    }
    return false;
  }
</script>
{% endblock %}