cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('account/', include('account.urls')),
    path('files/', include('files.urls', namespace='files')),
    path('search/', include('search.urls', namespace='search')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('discounts/', include('discounts.urls', namespace='discounts')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('warehouses/', include('warehouses.urls', namespace='warehouses')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

files/urls.py
from django.urls import path, include
from . import views

app_name = 'files'

urlpatterns = [
    path('list/', views.list_of_files, name='list_of_files'),
    path('upload/', views.add_to_database, name='view_file'),
    path('upload/<slug:file_slug>/', views.add_to_database, name='upload_file'),

    path('upload/new-product/<slug:file_slug>/<str:check>/', views.add_new_book_to_database, name='add_new_book_to_database_check'),
    path('upload/new-product/<slug:file_slug>/', views.add_new_book_to_database, name='add_new_book_to_database'),

    path('upload/new-product-2/<slug:file_slug>/<str:check>/', views.add_new_book_to_database_2, name='add_new_book_to_database_check_2'),
    path('upload/new-product-2/<str:product_isbn>/<int:quantity>/', views.update_isbn_duplicate, name='update_isbn_duplicate'),

    path('upload/name-correction/<slug:file_slug>/<str:check>/', views.name_correction, name='name_correction'),

    path('upload/correction_140/<slug:file_slug>/<str:check>/', views.correction_140, name='correction_140'),

    path('upload/new-product-3/<slug:file_slug>/<str:check>/', views.add_new_book_to_database_3, name='add_new_book_to_database_3'),

    path('upload/new-product-4/<slug:file_slug>/<str:check>/', views.add_new_book_to_database_4, name='add_new_book_to_database_4'),

    path('upload/used-product-isbn/<slug:file_slug>/<str:check>/', views.add_used_book_with_isbn, name='add_used_book_with_isbn'),
    path('upload/used-product-isbn-2/<slug:file_slug>/<str:check>/', views.add_used_book_with_isbn_2, name='add_used_book_with_isbn_2'),

    path('upload/used-product-no-isbn/<slug:file_slug>/<str:check>/', views.add_used_book_with_no_isbn, name='add_used_book_with_no_isbn'),
    path('upload/used-product-no-isbn-2/<slug:file_slug>/<str:check>/', views.add_used_book_with_no_isbn_2, name='add_used_book_with_no_isbn_2'),

    path('upload/add-craft/<slug:file_slug>/<str:check>/', views.add_crafts, name='add_crafts'),

    path('upload/update-used-book/<slug:file_slug>/<str:check>/', views.used_book_update, name='used_book_update'),

    path('upload/update-used-book-2/<slug:file_slug>/<str:check>/', views.used_book_update_2, name='used_book_update_2'),

    path('upload/update-duplicate-book-1/<slug:file_slug>/<str:check>/', views.duplicate_book_1, name='duplicate_book_1'),

    path('upload/check-category/<slug:file_slug>/<str:check>/<int:start>/<int:end>/', views.check_category, name='check_category'),

    path('upload/publishers/<slug:file_slug>/<str:check>/<int:start>/<int:end>/', views.update_publishers, name='update_publishers'),

]

orders/urls.py
from django.urls import path
from . import views
from . import report_views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),

    path('purchase/create/', views.purchase_create, name='purchase_create'),
    path('purchase/list/', views.purchase_list, name='purchase_list'),
    path('purchase/edit/<int:purchase_id>/', views.purchase_update, name='purchase_update'), # for updating main purchase model

    path('purchase/<int:purchase_id>/', views.purchase_details, name='purchase_details'),

    path('purchase/back-to-draft<int:purchase_id>/', views.back_to_draft_purchase, name='back_to_draft_purchase'),

    # path('purchase/<int:purchase_id>/add/<int:product_id>/', views.purchase_details, name='purchase_add_line'),
    path('purchase/add-line/<int:purchase_id>/<int:product_id>/<str:variation>/', views.purchase_line_add, name='purchaseline_add'),
    path('purchase/add-line/<int:purchase_id>/<int:product_id>/<str:variation>/<int:purchaseline_id>/', views.purchase_line_add, name='purchaseline_update'),
    path('purchaseline/remove/<int:purchaseline_id>/', views.purchaseline_remove, name='purchaseline_remove'),

    path('purchase/<int:purchase_id>/add/<int:product_id>/<str:variation>/', views.purchase_details, name='purchase_add_line_v'),

    path('purchase/price-management/<int:purchase_id>/<int:product_id>/', views.price_management, name='price_management'),
    path('purchase/price-management/remove-price/<int:purchase_id>/<int:product_id>/<str:variation>/', views.price_remove, name='price_remove'),

    path('purchase/checkout/<int:purchase_id>/', views.purchase_checkout, name='purchase_checkout'),

    path('report/sales-by-days/<int:days>/', report_views.sales_by_days, name='sales_by_days'),
    path('report/sales-by-date/<str:date>/', report_views.sales_by_days, name='sales_by_date'),

    path('report/best_selling_books/', report_views.best_selling_books, name='best_selling_books'),
]

shop/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views

app_name = 'shop'

urlpatterns = [
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/<int:image_id>/', views.product_detail, name='product_detail_image'),
    path('product/<int:product_id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('', views.temp_home, name='temp_home'),
    # path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('products/<str:category_slug>/', views.product_list, name='products_list'),

    path('book-search/<str:state>/', views.store_book_search, name='store_book_search'),

    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    path('categories/', views.category_list, name="category_list"),
    path('publishers/', views.publisher_list, name="publisher_list"),
    path('publishers/products/<int:publisher_id>/', views.publisher_products, name="publisher_products"),
    path('publishers/create/', views.publisher_create, name="publisher_create"),
    path('publishers/update/<int:publisher_id>', views.publisher_create, name="publisher_update"),
]

staff/urls.py
from django.urls import path

from . import views
from .views import ProductCreate
from warehouses.views import refund_from_client, refund_list_client

app_name = 'staff'


urlpatterns = [
    # path('sales/', views.sales, name='sales_list'),
    path('orders/details/<int:pk>/', views.order_detail_for_admin, name='order_detail_for_admin'),
    path('orders/shipping/<int:order_id>/', views.order_shipping, name='order_shipped'),

    path('orders/full-shipped-list/', views.full_shipped_list, name='full_shipped_list'),
    path('orders/full-shipped-list/<str:date>/', views.full_shipped_list, name='full_shipped_list_date'),
    # path('orders/sipping/<int:order_id>/', views.order_shipping, name='order_shipping'),
    path('orders/drafts/', views.draft_orders, name='draft_orders'),
    path('orders/remove-draft/<int:order_id>/', views.remove_draft_order, name='remove_draft_order'),

    path('orders/create/', views.order_create, name='order_create'),
    # path('orders/', views.orders, name='order_list'),
    # path('orders/<str:channel>/', views.orders, name='order_list_by_channel'),
    # path('orders/<str:channel>/<str:period>/', views.orders, name='order_list_by_channel_period'),
    path('orders/<str:channel>/<str:period>/', views.orders, name='order_list'),
    path('orders/<str:channel>/<str:period>/<str:filter>/', views.orders, name='order_list_filter'),

    path('sales/countries/', views.order_list_by_country, name='order_list_by_country'),
    path('sales/countries/<str:country_code>/', views.order_list_by_country, name='order_list_by_country'),

    path('sales/vendor/', views.sales_by_vendor, name='sales_by_vendor'),
    path('sales/vendor/<int:vendor_id>/<str:date>/', views.sales_by_vendor, name='sales_by_vendor'),


    path('invoice/create/', views.invoice_create, name='invoice_create'),
    path('invoice/create/<int:order_id>/', views.invoice_create, name='invoice_create'),
    path('invoice/create/<int:order_id>/<int:book_id>/', views.invoice_create, name='invoice_add_book'),
    path('invoice/create/<int:order_id>/<int:book_id>/<str:variation>/', views.invoice_create, name='invoice_add_book_v'),

    path('invoice/create/new_order/<int:book_id>/', views.invoice_create, name='invoice_new_add_book'),
    path('invoice/create/new_order/<int:book_id>/<str:variation>/', views.invoice_create, name='invoice_new_add_book_v'),

    path('invoice/create/<int:order_id>/add-client/', views.invoice_create_add_client, name='invoice_add_client'),
    path('invoice/create/<int:order_id>/add-client/<int:client_id>/', views.invoice_create_add_client, name='invoice_add_client_ok'),
    path('invoice/remove-client/<int:order_id>/', views.remove_client_from_order, name='remove_client_from_order'),

    path('invoice/create/line-update/<int:order_id>/<int:orderline_id>/', views.orderline_update, name='orderline_update'),
    path('invoice/checkout/<int:order_id>/', views.invoice_checkout, name='invoice_checkout'),
    path('invoice/checkout/<int:order_id>/<int:client_id>/', views.invoice_checkout, name='invoice_checkout_client'),
    path('invoice/checkout/credit-pay/<int:order_id>/<int:client_id>/', views.invoice_checkout_credit, name='invoice_checkout_client_credit'),
    path('invoice/checkout/credit-remove/<int:order_id>/', views.invoice_remove_credit, name='invoice_remove_credit'),

    path('invoice/back-to-draft/<int:order_id>/', views.invoice_back_to_draft, name='invoice_back_to_draft'),
    path('invoice/payment-manage/<int:order_id>/', views.order_payment_manage, name='order_payment_manage'),

    path('warehouse/', views.warehouse, name='warehouse'),
    path('warehouse/sold-products/<int:days>/', views.sold_products, name='sold_products'),
    path('warehouse/sold-products/date/<str:date>/', views.sold_products, name='sold_products_date'),
    path('warehouse/sold-products/period/<str:period>/', views.sold_products, name='sold_products_date_period'),

    path('warehouse/purchased-products/', views.purchased_products, name='purchased_products'),
    path('warehouse/refund/client/', refund_from_client, name="refund_from_client"),
    path('warehouse/refund/client/list/', refund_list_client, name="refund_list_client"),

    path('warehouse/zero-stock-list/', views.zero_stock_list, name="zero_stock_list"),

    path('products/', views.products, name='products'),
    path('products/create/', views.product_create, name='product_create'),
    # path('products/update/<int:product_id>/', views.product_update, name='product_update'),
    path('products/update/<int:product_id>/', views.product_create, name='product_update'),
    path('products/image-management/<int:product_id>/', views.image_management, name='image_management'),
    path('products/image-remove/<int:image_id>/<int:product_id>/', views.image_remove, name='image_remove'),
    path('products/price-show/<int:product_id>/', views.product_price_show, name='product_price_show'),

    path('products/collection-management/', views.collection_management, name='collection_management'),
    path('products/collection-management/edit/<int:product_id>/', views.collection_management_edit, name='collection_management_edit'),
    path('products/collection-management/edit/<int:product_id>/<str:product_isbn>/', views.collection_management_remove, name='collection_management_remove'),

    path('products/reports/', views.product_reports, name='product_reports'),

    path('categories/', views.category_list, name='categories'),
    path('category/create/', views.category_create, name='category_create'),

    path('vendor/list/', views.vendor_list, name='vendor_list'),
    path('vendor/add/', views.vendor_add, name='vendor_add'),
    path('vendor/edit/<int:vendor_id>/', views.vendor_edit, name='vendor_edit'),

    path('products/used-book/price-management/<int:product_id>/', views.used_book_prices, name="used_book_prices"),
    path('products/price-stock-management/<int:product_id>/', views.product_stock_price_edit, name="product_stock_price_edit"),

    path('products/crafts/', views.craft_list, name="craft_list"),
    path('products/crafts-update/<int:craft_id>/', views.craft_update, name="craft_update"),
    path('products/crafts-create/', views.craft_update, name="craft_create"),
]

templates/_base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html dir="rtl">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Open graph -->
  <meta property="og:title" content="{% trans 'Ketab Damavand' %}" />
  <meta name="description" property="og:description" content="{% trans 'Ketab Damavand' %}">
  <meta property="og:image" content="{% static 'img/logo.jpg' %}" />
  <meta property="og:image:alt" content="{% trans 'Ketab Damavand logo' %}" />

  <!-- favicon -->
  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icon/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icon/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icon/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icon/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icon/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icon/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icon/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icon/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icon/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icon/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'icon/manifest.json' %}">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{% static 'icon/ms-icon-144x144.png' %}">
  <meta name="theme-color" content="#ffffff">

  <!-- css files -->
  <link href="{% static 'css/bootstrap.rtl.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-grid.rtl.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-utilities.rtl.min.css' %}" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="{% static 'css/base.css' %}" rel="stylesheet">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-F9RJ6DQ80X"></script>
  <script defer>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-F9RJ6DQ80X');
  </script>

  {% block head %}{% endblock %}

  <title>{% block title %}{% endblock %} | {% trans 'Ketab Damavand' %}</title>
</head>

<body>
  <header class="mb-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid bg-main-color border-bottom border-2 border-dark">
        <a class="navbar-brand p-1 fw-bolder" href="{% url 'shop:home' %}"><img src="{% static 'img/logo.jpg' %}" alt="{% trans 'Ketab Damavand' %}" class="rounded" width="80px;" height="auto"></a>
        <!-- navbar button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:products_list' 'new' %}">{% trans 'New' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:products_list' 'used' %}">{% trans 'Used' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:products_list' 'کودک-و-نوجوان' %}">{% trans 'Children & Youth' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:category_list' %}">{% trans 'Categories' %}</a>
            </li>
          </ul>

        </div>
        <div class="cart">
          {% with total_items=cart|length %}
          <img src="{% static 'img/cart.png' %}" width="30px" height="auto" alt="cart">
          {% if total_items > 0 %}
          <a href="{% url 'cart:cart_detail'%}" class="position-relative">
            <span class="position-absolute top-0 start-50 translate-middle badge rounded-pill bg-danger">

              {{ total_items }}
              <span class="visually-hidden">{% trans 'items in cart' %}</span>
            </span>
            {% comment %}
            {{ total_items }} {% trans 'item' %}, {{ cart.get_total_price }} {% trans 'Toman' %}
            {% blocktrans with total=cart.get_total_price count items=total_items %}
            {{ total_items }} item, {{ cart.get_total_price }} {% trans 'Toman' %}
            {% endblocktrans %}
            {% endcomment %}
          </a>
          {% else %}

          {% endif %}
          {% endwith %}
        </div>
        <div class="p-2">

          {% if request.user.is_authenticated %}
          <a href="{% url 'dashboard' %}" <b>{{ request.user }}</b></a>
          <a href="{% url 'logout' %}" class="">
            <img src="{% static 'img/logout.png' %}" width="30px" height="auto" alt="logout"></a>
          {% else %}
          <a href="{% url 'register' %}">
            <img src="{% static 'img/signup.png' %}" width="40px" height="auto" alt="signup"></a>
          <a href="{% url 'login' %}" class="">
            <img src="{% static 'img/login.png' %}" width="30px" height="auto" alt="login"></a>
          {% endif %}

        </div>

      </div>

    </nav>
    {% comment %}
    <!-- search bar -->
    <div class="container my-2">
      <form class="d-flex " action="{% url 'search:product_search' %}" method="GET">
        <input class="form-control me-2" type="search" placeholder="نام کتاب، پدیدآورنده، ناشر" aria-label="Search">
        <button class="btn btn-outline-secondary" value="query" type="submit">{% trans 'Search' %}</button>
      </form>
    </div>
    {% endcomment %}
    {% if messages %}
    <div id="hideme" class="hide-class">

      <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
          <a href="#" class="close" class="toast" role="alert" aria-live="assertive" aria-atomic="true">x</a>
        </li>
        {% endfor %}
      </ul>

    </div>
    {% endif %}
    {% if user.is_staff %}
    <div class="m-2">
      <a href="{% url 'staff:draft_orders' %}" class="btn btn-sm btn-outline-secondary {% block slaes-btn %}{% endblock %}">{% trans 'Sales' %}</a>
      <a href="{% url 'staff:order_list' period='all' channel='all' %}" class="btn btn-sm btn-outline-secondary {% block orders-btn %}{% endblock %}">{% trans 'Orders' %}</a>
      <a href="{% url 'orders:purchase_list' %}" class="btn btn-sm btn-outline-secondary {% block purchases-btn %}{% endblock %}">{% trans 'Purchase' %}</a>
      <a href="{% url 'staff:warehouse' %}" class="btn btn-sm btn-outline-secondary {% block warehouses-btn %}{% endblock %}">{% trans 'Warehouse' %}</a>
      <a href="{% url 'staff:products' %}" class="btn btn-sm btn-outline-secondary {% block products-btn %}{% endblock %}">{% trans 'Products' %}</a>
      <a href="{% url 'client_list' %}" class="btn btn-sm btn-outline-secondary {% block clients-btn %}{% endblock %}">{% trans 'Clients' %}</a>
      <a href="{% url 'tickets:tickets_list' %}" class="btn btn-sm btn-outline-secondary {% block tickets-btn %}{% endblock %}">{% trans 'Tickets' %}</a>
      {% if request.user.is_manager or request.user.is_superuser %}
      <a href="{% url 'staff:product_reports' %}" class="btn btn-sm btn-outline-secondary ">{% trans 'Prodct reports' %}</a>
      <a href="{% url 'orders:sales_by_days' days=365 %}" class="btn btn-sm btn-outline-secondary {% block reports-btn %}{% endblock %}">{% trans 'Reports' %}</a>
      {% endif %}

      {% block staff_tab %}{% endblock %}
      {% if request.user.is_superuser %}
      <a href="{% url 'admin:index' %}" class="btn btn-sm btn-dark btn-outline-secondary ">{% trans 'Admin' %}</a>
      <a href="{% url 'rosetta-old-home-redirect' %}" class="btn btn-sm btn-dark btn-outline-secondary ">Rosetta</a>
      <a href="{% url 'files:list_of_files' %}" class="btn btn-sm btn-dark btn-outline-secondary ">Files</a>
      {% endif  %}
    </div>
    {% endif %}


  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer class="footer">
    <div class="mt-3 container-fluid bg-second-color">
      <div class="row row-cols-md-3 p-5">
        <div class="col text-light">
          <p>{% trans 'How to order books' %}</p>
          <p>{% trans 'Website rules' %}</p>
          <p>{% trans 'Q&A' %}</p>
          <p>{% trans 'Contact us' %}</p>

        </div>
        <div class="col text-light">
          <p class="fw-bold">{% trans 'Ketabe Damavand' %}</p>
          <p>{% trans 'Address' %} :
            <span class="text-center">{% trans '16 Azar St.' %}, {% trans 'Edward Brown St.' %}, {% trans 'No.7' %}</span>


          </p>
          <p>{% trans 'Phone' %} :
            <br><span>{% trans 'Bookstore' %} :</span>
            <br><a href="tel:+982166981024" dir="ltr">+9821 66981024</a>
            <br>
            <br>
            {% comment %}
            <span>{% trans 'Orders followup' %} :</span>
            <br><a href="tel:+989123487091" dir="ltr">+98 912 3487091</a>
            {% endcomment %}
          <p>
            <a href="mailto:info@ketabedamavand.com">info@ketabedamavand.com</a>
          </p>

          </p>
        </div>
        <div class="col text-light social-network">
          <p class="fw-bold">{% trans 'Social Media' %}</p>

          <span>{% trans 'Ketabe Damavand' %}</span> <br>
          <a href="https://t.me/bahmanbooks/">
            <i class="fa fa-send"></i>
          </a>
          <br>
          <br>

          <span>{% trans 'Order books in social media' %}</span> <br>
          <a href="https://instagram.com/bahmanbookz/">
            <i class="fa fa-instagram"></i>
          </a>
          <a href="https://t.me/bahmanbookz/">
            <i class="fa fa-send"></i>
          </a>
          <a href="https://twitter.com/bahmanbooks/">
            <i class="fa fa-twitter"></i>
          </a>
          <br>
          <br>

          <span>{% trans 'Bahman Daroshafaei in social media' %}</span><br>
          <a href="https://t.me/bahmanshafa/">
            <i class="fa fa-send"></i>
          </a>
          <a href="https://instagram.com/bahman.daroshafaei/">
            <i class="fa fa-instagram"></i>
          </a>
          <a href="https://twitter.com/bahmandaroshafa/">
            <i class="fa fa-twitter"></i>
          </a>

        </div>
      </div>
    </div>
    <div class="row bg-dark text-center">
      <p class="text-light pt-3">{% trans 'Ketabe Damavand'%} 1400</p>
    </div>

  </footer>

  <script src="{% static 'js/bootstrap.min.js' %}" async></script>
  {% comment %}
  <script defer>
    setTimeout(function() {
      document.getElementById('hideme').className = 'waa';
    }, 2500);
  </script>
  {% endcomment %}
  {% block script %}
  {% endblock %}
</body>

</html>

templates/home.html
{% extends "_base.html" %}

{% load i18n %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Home' %}{% endblock %}

{% block content %}
<div class="row m-4 text-center">
  <form action="{% url 'search:product_search'%}" method="get" class="">
    <div class="row">
      <div class="col-md-9">
        {% crispy search_form %}
      </div>
      <div class="col-md-3">
        <input class="btn btn-outline-secondary form-control" type="submit" value="{% trans 'Search' %}">
      </div>
    </div>
  </form>
</div>
<div class="container-fluid overflow-hidden">
  <div class="row gy-2">
    {% comment %}
    <div class="col-md-3">
      {% include 'shop/_filter_sidebar.html'%}
    </div>
    {% endcomment %}
    <div class="col-md-12">
      {% include 'shop/_product_list.html' %}
    </div>
  </div>
</div>

{% endblock %}

templates/temp_home.html
{% extends "_temp_base.html" %}

{% load i18n %}

{% load static %}

{% block title %}{% trans 'Home' %}{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
<div class="row text-center">
  <p class="h3 p-5" dir="ltr">سایت کتاب دماوند به‌زودی راه‌اندازی می‌شود</p>  
  <br>
  <br>
  <br>
  <br>

</div>

</div>

{% endblock %}