cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('account/', include('account.urls')),
    path('files/', include('files.urls', namespace='files')),
    path('search/', include('search.urls', namespace='search')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('discounts/', include('discounts.urls', namespace='discounts')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('warehouses/', include('warehouses.urls', namespace='warehouses')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path

from . import views


app_name = 'tickets'


urlpatterns = [
    path('', views.tickets_list, name="tickets_list"),
    path('filter/<str:filter>', views.tickets_list, name="tickets_list_filter"),
    path('details/<int:ticket_id>/', views.ticket_details, name="ticket_details"),
    path('create/', views.create_ticket, name="create_ticket"),
]

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path('pdf/<int:order_id>/', views.make_invoice_pdf, name="make_invoice_pdf"),
    path('pdf/<int:order_id>/print/', views.print_invoice, name="print_invoice"),
    path('pdf/a4/<int:order_id>/', views.make_invoice_pdf_a4, name="make_invoice_pdf_a4"),

    path('print/address/<int:client_id>/<str:kind>/', views.print_address, name="print_address"),

    path('order-export/<str:criteria>/', views.order_export_excel, name="order_export_excel"),
    path('order-export/<str:criteria>/<str:date>/', views.order_export_excel, name="order_export_excel_date"),

    path('draft-order-export/', views.draft_order_export_excel, name="draft_order_export_excel"),
    path('publishers-export/', views.export_publisher, name="export_publisher"),

    path('product-export/', views.product_export_excel, name="product_export_excel"),
    path('used-product-without-price-export/<str:filter>/', views.product_export_excel, name="used_noprice_export_excel"),
    path('used-product-all-export/<str:filter>/', views.product_export_excel, name="used_all_export_excel"),

    path('used-product-before-5/', views.used_product_before_5, name="used_product_before_5"),

    path('qrcode/create/<int:order_id>/<int:payment_id>/', views.qrcode_create, name='qrcode_create'),

    path('export-sold-products/<int:days>/', views.export_excel_sold_products, name="export_excel_sold_products"),
    path('export-sold-products/date/<str:date>/', views.export_excel_sold_products, name="export_excel_sold_products_date"),
    path('export-sold-products/period/<str:period>/', views.export_excel_sold_products, name="export_excel_sold_products_date_period"),

    path('duplicate-book-name/', views.duplicate_book_name, name="duplicate_book_name"),
    path('duplicate-book-name/export', views.duplicate_book_name_export, name="duplicate_book_name_export"),
]

tickets/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django.core.validators import MinValueValidator , MaxValueValidator


from tools.gregory_to_hijry import hij_strf_date, greg_to_hij_date


class Ticket(models.Model):
    PRIORITY_CHOICES = (
        ('normal', _('Normal')),
        ('medium', _('Medium')),
        ('high', _('High')),
    )

    name = models.CharField(
        max_length=100,
    )
    description = models.TextField()
    priority = models.CharField(
        max_length=20,
        default='normal',
        choices=PRIORITY_CHOICES
    )
    rank = models.IntegerField(
        default=5,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(10)
         ]
    )
    url = models.URLField(
        null=True,
        blank=True
    )
    file = models.FileField(
        upload_to='tickets/files',
        null=True,
        blank=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )
    registrar = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name='tickets_registrar',
        blank=True,
        null=True
    )
    active = models.BooleanField(
        default=True
    )
    is_checked = models.BooleanField(
        default=False
    )
    is_solved = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.name

    def get_fa_created(self):
        return hij_strf_date(greg_to_hij_date(self.created.date()), '%-d %B %Y')

tickets/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
# from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Ticket


class CreateTicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
            'name', 'priority', 'rank',
            'description',
            'url', 'file',
        ]
        widgets = {
            'url': forms.TextInput(attrs={'placeholder': _('The URL of the page that has the problem')})
        }
        help_texts ={
            'file': _('The file or screenshot that help to find the problem'),
            'rank': _('select from 1 to 10 tha 1 is the highest rank and 10 is the lowest rank'),

        }
        # validators = {
        #     'rank': [MinValueValidator(1), MaxValueValidator(10)]
        # }

tickets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

from .models import Ticket
from .forms import CreateTicketForm

@staff_member_required
def tickets_list(request, filter=None):
    tickets = Ticket.objects.all().order_by('priority', 'rank' )
    if filter in ('normal', 'medium', 'high'):
        tickets = tickets.filter(priority=filter)


    return render(
        request,
        'tickets/tickets_list.html',
        {
            'tickets': tickets,
        }
    )


@staff_member_required
def ticket_details(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)
    if request.method == 'POST':
        ticket_form = CreateTicketForm(
            instance=ticket,
            data=request.POST,
            files=request.FILES
        )
        if ticket_form.is_valid():
            ticket_form.save()
            # new_ticket.registrar = request.user
            # new_ticket.save()
            messages.success(request, _('Ticket updated'))
            return redirect('tickets:tickets_list')
    else:
        ticket_form = CreateTicketForm(instance=ticket)
    return render(
        request,
        'tickets/ticket_details.html',
        {
            'ticket': ticket,
            'ticket_form': ticket_form,
        }
    )


@staff_member_required
def create_ticket(request):
    if request.method == 'POST':
        ticket_form = CreateTicketForm(
            data=request.POST,
            files=request.FILES
        )
        if ticket_form.is_valid():
            new_ticket = ticket_form.save(commit=False)
            new_ticket.registrar = request.user
            new_ticket.save()
            messages.success(request, _('Ticket created'))
            return redirect('tickets:tickets_list')
    else:
        ticket_form = CreateTicketForm()
    return render (
        request,
        'tickets/create_ticket.html',
        {
            'ticket_form': ticket_form,
        }
    )

templates/tickets/create_ticket.html
{% extends "_base.html" %}

{% load i18n %}

{% load static %}

{% load humanize %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Create ticket' %}{% endblock %}

{% block tickets-btn %}btn-secondary text-dark{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
  <div class="row">
    <div class="col-md-1">
      {% include "staff/sidebar_staff.html" with barName="tickets" %}
    </div>
    <div class="col-md-11">
      <h2>{% trans 'Create ticket' %}</h2>
        <div class="w-50">
          <form class="" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ ticket_form | crispy }}
            <input type="submit" name="" class="btn btn-outline-success" value="{% trans "Save" %}">
          </form>

        </div>
      </div>
    </div>


  </div>

</div>
{% endblock %}
{% block script %}

{% endblock %}

templates/tickets/ticket_details.html
{% extends "_base.html" %}

{% load i18n %}

{% load static %}

{% load humanize %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Ticket details' %}{% endblock %}

{% block tickets-btn %}btn-secondary text-dark{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
  <div class="row">
    <div class="col-md-1">
      {% include "staff/sidebar_staff.html" with barName="tickets" %}
    </div>
    <div class="col-md-11">
      <h2>{% trans 'Ticket details' %}: {{ ticket.pk }} - {{ ticket }}</h2>
      <div class="table-responsive">
        <table class="table table-striped table-responsive w-50">
          <tbody>
            <tr>
              <td>{% trans "Name" %}</td>
              <td><a href="">{{ ticket }}</a></td>
            </tr>
            <tr>
              <td>{% trans "Priority" %}</td>
              <td>{{ ticket.get_priority_display }}</td>
            </tr>
            <tr>
              <td>{% trans "Rank" %}</td>
              <td>{{ ticket.rank }}</td>
            </tr>
            <tr>
              <td>{% trans "Registrar" %}</td>
              <td>{{ ticket.registrar.first_name }}</td>
            </tr>
            <tr>
              <td>{% trans "Active" %}</td>
              <td>{% if ticket.active %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
            </tr>
            <tr>
              <td>{% trans "Is checked" %}</td>
              <td>{% if ticket.is_checked %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
            </tr>
            <tr>
              <td>{% trans "Is solved" %}</td>
              <td>{% if ticket.is_solved %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
            </tr>
            <tr>
              <td>{% trans "File" %}</td>
              <td>{% if ticket.file %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
            </tr>
            <tr>
              <td>{% trans "Date" %}</td>
              <td>{{ ticket.get_fa_created }}</td>
            </tr>
          </tbody>
        </table>
        <div class="border p-2">
          <p>
            {% trans "Description" %}: <br>
            {{ ticket.description | linebreaksbr }}
          </p>
          <hr>
          {% if ticket.url %}
          <p>
            <p>
              URL:
            </p>
            <a href="{{ ticket.url }}" target="_blank">{{ ticket.url }}</a>
          </p>
          {% endif %}
          {% if ticket.file %}
          <p>
          <p> {% trans "File" %}:
          </p>
          <a href="{{ ticket.file.url }}" target="_blank">{{ ticket.file.name }}</a>
          </p>
          {% endif %}

        </div>

        {% if request.user.is_superuser or request.user.is_manager %}
        <h3 class="mt-4">{% trans 'Edit ticket' %}</h3>
          <div class="w-50">
            <form class="" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ ticket_form | crispy }}
              <input type="submit" name="" class="btn btn-outline-success" value="{% trans "Save" %}">
            </form>
          </div>
          {% endif %}

      </div>
      {% if page %}
      {# {% include "shop/pagination.html" with page=products %} #}
      {% endif %}
    </div>


  </div>

</div>
{% endblock %}
{% block script %}

{% endblock %}

templates/tickets/tickets_list.html
{% extends "_base.html" %}

{% load i18n %}

{% load static %}

{% load humanize %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Tickets' %}{% endblock %}

{% block tickets-btn %}btn-secondary text-dark{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
  <div class="row">
    <div class="col-md-1">
      {% include "staff/sidebar_staff.html" with barName="tickets" %}
    </div>
    <div class="col-md-11">
      <h2>{% trans 'List of tickets' %}</h2>
      <div class="">
        <p>
          <span>{% trans "Priority filters" %}:</span>
          <a href="{% url 'tickets:tickets_list_filter' filter='high' %}">{% trans "High" %}</a> |
          <a href="{% url 'tickets:tickets_list_filter' filter='medium' %}">{% trans "Medium" %}</a> |
          <a href="{% url 'tickets:tickets_list_filter' filter='normal' %}">{% trans "Normal" %}</a>
        </p>

      </div>
      {% comment %}
      <div class="my-3">
        {% if request.user.is_superuser %}
        <p><a href="{% url 'tools:product_export_excel' %}" class=""><img src="{% static 'img/excel-icon.png' %}" alt="Excel icon" width="32px" height="auto">{% trans 'All products' %} <span
              class="text-danger">{% trans 'Could be very slow or it may crash' %}</span></a>
        <a href="{% url 'tools:used_noprice_export_excel' filter='used-noprice' %}" class=""><img src="{% static 'img/excel-icon.png' %}" alt="Excel icon" width="32px" height="auto">{% trans 'Used products without price' %}</a>
        <a href="{% url 'tools:used_all_export_excel' filter='used-all' %}" class=""><img src="{% static 'img/excel-icon.png' %}" alt="Excel icon" width="32px" height="auto">{% trans 'All used products' %}</a></p>
        {% endif %}
      </div>
      <p>
      {% if page %}
        {% trans "All products" %}
      {% else %}
        {% trans "Search results" %}
      {% endif %}
      <span>: {{ counts | intcomma:False }}</span>
    </p>

      <form class="" action="." method="post">
        <div class="row">

          <div class="col-md-9">
            {{ search_form | crispy }}
            {% csrf_token %}
          </div>

          <div class="col-md-3">
            <input class="btn btn-outline-secondary form-control" type="submit" name="book" value="{% trans 'Submit' %}">
          </div>
        </div>

      </form>
      {% endcomment %}
      <div class="table-responsive">
        <table class="table table-striped table-responsive">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">{% trans 'Name' %}</th>
              <th scope="col">{% trans 'Priority' %}</th>
              <th scope="col">{% trans 'Rank' %}</th>
              <th scope="col">{% trans 'Registrar' %}</th>
              <th scope="col">{% trans 'Active' %}<span class="small"></span></th>
              <th scope="col">{% trans 'Is checked' %}</th>
              <th scope="col">{% trans 'Is solved' %}</th>
              <th scope="col">{% trans 'File' %}</th>
              <th scope="col">{% trans 'Created date' %}</th>
            </tr>
          </thead>
          <tbody>
            {% for ticket in tickets %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><a href="{% url 'tickets:ticket_details' ticket.id %}">{{ ticket }}</a></td>
              <td>{{ ticket.get_priority_display }}</td>
              <td>{{ ticket.rank }}</td>
              <td>{{ ticket.registrar.first_name }}</td>
              <td>{% if ticket.active %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
              <td>{% if ticket.is_checked %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
              <td>{% if ticket.is_solved %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
              <td>{% if ticket.file %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
              <td>{{ ticket.get_fa_created }}</td>


            </tr>
            {% endfor %}

            {% comment %}
            {% endcomment %}
          </tbody>
        </table>
      </div>
      {% if page %}
      {# {% include "shop/pagination.html" with page=products %} #}
      {% endif %}
    </div>


  </div>

</div>
{% endblock %}
{% block script %}

{% endblock %}